sqs-provider: aws


main-queue:
  sqs-queue: ${main.queue}
  access-key-id: ${main.queue.access.key.id}
  secret-access-key: ${main.queue.secret.access.key}
  region: eu-west-2

dlq:
  sqs-queue: ${dlq.queue}
  access-key-id: ${dlq.access.key.id}
  secret-access-key: ${dlq.secret.access.key}
  region: eu-west-2