spring:

  jpa:
    show-sql: false

  datasource:
    url: 'jdbc:h2:mem:hmpps-tier-sqs-tool;MODE=PostgreSQL;'
    username: probation
    password: tiering

  h2:
    console:
      enabled: true
      path: /h2-console-sqs-tool

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

logging:
  level:
    uk.gov: DEBUG

server:
  shutdown: immediate