sqs-provider: localstack

main-queue:
  endpoint: http://localhost:4576
  sqs-queue: http://localhost:4576/queue/Digital-Prison-Services-dev-hmpps_tier_offender_events_queue
  region: eu-west-2

dlq:
  endpoint: http://localhost:4576
  sqs-queue: http://localhost:4576/queue/Digital-Prison-Services-dev-hmpps_tier_offender_events_queue_dl
  region: eu-west-2