# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/hmpps/hmpps-tier-sqs-tool
  tag: latest
  port: 8080

env:
  JAVA_OPTS: "-Xmx512m"
