DROP TABLE IF EXISTS CALCULATION_REQUEST;

CREATE TABLE CALCULATION_REQUEST
(
    ID         SERIAL PRIMARY KEY,
    CRN        VARCHAR   NOT NULL,
    CREATED    TIMESTAMP NOT NULL,
    PROCESSED  TIMESTAMP,
    MESSAGE_ID VARCHAR
);

CREATE
INDEX CALCULATION_REQUEST_PROCESSED on CALCULATION_REQUEST(PROCESSED);